name: destiny2_slack_bot
author: P.Y. Laligand
version: 0.0.1
description: A Slack bot for Destiny2 communities.
dependencies:
  destiny2_api:
    git:
      url: https://github.com/pylaligand/destiny2-dart-api-client.git
      ref: master
  heroku_slack_bot:
    git:
      url: https://github.com/pylaligand/heroku-slack-bot.git
      ref: master
